create table quiz(
 id_quiz int not null auto_increment primary key, 
 quiero_conocer varchar(150), 
 serio_casual varchar(50), 
 edad_preferida varchar(50), 
 ocupacion_preferida varchar(50), 
 caracteristicas1 varchar(50), 
 caracteristicas2 varchar(50), 
 caracteristicas3 varchar(50), 
 lugares_frecuenta varchar(50), 
 cita_donde varchar(50), 
 cita_ideal text, 
 nombre varchar(50), 
 email varchar(50), 
 edad varchar(50), 
 celular varchar(50), 
 skype varchar(50),
 facebook varchar(50), 
 ocupacion varchar(50), 
 barrio varchar(50), 
 foto1 varchar(150), 
 foto2 varchar(150), 
 foto3 varchar(150) 
 )